### ISSUE TITLE
Extend list view with introductory message

### ISSUE THREAD

**Issue by hschne** [ItalyPaleAle/hereditas#4]
First of all I want to let you know that I really appreciate your work. I have been looking into solutions to dealing with digital legacy for a while, and this really seems like a great tool to do so. 

Now for a suggestion: It would be a nice touch to be able to include customizable content in the initial list view, for example a welcome message or further instructions. 

The use case being that users who just gained access to the box can be introduced into which contents can be found there. Instead of a list of content they are not familiar with they could be shown a welcoming message or something along those lines. 

This information could also be provided by the initial email telling the user about the box. However, I can't really maintain that information and would have to send 'content-updates' if the contents of the box change in any way - not so great. 

As a creator of the box I could provide a specific markdown file (`welcome.md`?) that will always be rendered on top of the initial list view.

**Comment by ItalyPaleAle** [comment]
I think this is a good idea and it shouldn’t be hard to implement. I’ll look into this as part of the UI improvements in version 0.2
